// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwtIgA_ZMattjJNnXRZuKPGudeJXWW4yg',
    appId: '1:498318171253:web:51b615cc8d3ca79297ec3c',
    messagingSenderId: '498318171253',
    projectId: 'println-auth',
    authDomain: 'println-auth.firebaseapp.com',
    storageBucket: 'println-auth.firebasestorage.app',
    measurementId: 'G-8186YPJ0PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPf_OKCncHgzgS7iUJYkKJoLcoImFbysk',
    appId: '1:498318171253:android:c46b989df0f1112897ec3c',
    messagingSenderId: '498318171253',
    projectId: 'println-auth',
    storageBucket: 'println-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAajGPPd7D3EXHA3CJYoGsKrpLBEJwl_rY',
    appId: '1:498318171253:ios:f937e97d5473a46797ec3c',
    messagingSenderId: '498318171253',
    projectId: 'println-auth',
    storageBucket: 'println-auth.firebasestorage.app',
    iosBundleId: 'com.example.println',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAajGPPd7D3EXHA3CJYoGsKrpLBEJwl_rY',
    appId: '1:498318171253:ios:f937e97d5473a46797ec3c',
    messagingSenderId: '498318171253',
    projectId: 'println-auth',
    storageBucket: 'println-auth.firebasestorage.app',
    iosBundleId: 'com.example.println',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwtIgA_ZMattjJNnXRZuKPGudeJXWW4yg',
    appId: '1:498318171253:web:69d849e932e6483097ec3c',
    messagingSenderId: '498318171253',
    projectId: 'println-auth',
    authDomain: 'println-auth.firebaseapp.com',
    storageBucket: 'println-auth.firebasestorage.app',
    measurementId: 'G-7SL15YCDCF',
  );
}
